steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/rafikarhaiem/GestionClub"]
    env: ["PROJECT_ROOT=github.com/rafikarhaiem/GestionClub"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/qwiklabs-gcp-00-3dad53904c6f/GestionClub:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/qwiklabs-gcp-00-3dad53904c6f/GestionClub:$REVISION_ID"

